/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ch.so.agi.oereb;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Assertions;

class LibraryTest {
//    @Test
//    void testSomeLibraryMethodFoo() {
//        Library classUnderTest = new Library();
//        Assertions.assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
//
//
//        //
//    }
}
