name: oereb-test-suite

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Set up JDK 15
        uses: actions/setup-java@v1
        with:
          java-version: 15
      - name: Build with Gradle
        run: ./gradlew clean lib:test 
        #if: ${{ github.ref == 'refs/heads/master' }}  
        env:
          GITHUB_RUN_NUMBER: ${{ github.run_number }}
      - uses: actions/upload-artifact@v2
        if: ${{ failure() }}
        with:
          name: reports
          path: lib/build/reports/tests/ # or path/to/artifact
